apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      restartPolicy: Always
      serviceAccountName: traefik-account
      containers:
      - name: traefik
        image: traefik:v2.10
        ports:
        - containerPort: 8000
          name: web
        - containerPort: 8080
          name: admin
        args:
        - --api.insecure=true
        - --providers.kubernetesingress=true
        - --entrypoints.web.address=:8000
        - --log.level=INFO
        - --api.dashboard=true
